# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171208_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpart',
            name='price',
            field=models.FloatField(),
        ),
    ]
