# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171213_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparts', to='projects.Project'),
        ),
    ]
