# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_participation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='user',
            new_name='author',
        ),
    ]
